--EXERCICIO AULA 3
--APROVEITANDO A ESTRUTURA DO EXERCICIO AULA2
--CRIANDO TABELA CATEGORIA
CREATE TABLE [TESTE].[DBO].[CATEGORIA]
(
COD_CATEGORIA INT ,
CATEGORIA CHAR(255),
CONSTRAINT PK_CATEGORIA_CHAVE_PRIMARIA PRIMARY KEY (COD_CATEGORIA)
);
--DROP
DROP TABLE [TESTE].[DBO].[CATEGORIA]

--CRIANDO TABELA MATERIA_PRIMA
CREATE TABLE [TESTE].[DBO].[MATERIA_PRIMA]
(
COD_MATERIA_PRIMA INT,
MATERIA_PRIMAA CHAR(255),
CONSTRAINT PK_MATERIA_PRIMA_CHAVE_PRIMARIA PRIMARY KEY (COD_MATERIA_PRIMA)
);
--DROP
DROP TABLE [TESTE].[DBO].[MATERIA_PRIMA]

--CRIANDO TABELA PRODUTO
CREATE TABLE PRODUTO (
 COD_PRODUTO INT CONSTRAINT PK_PRO_CODPRO PRIMARY KEY,
 COD_CATEGORIA INT CONSTRAINT FK_PRODUTO_CATEGORIA REFERENCES [TESTE].[DBO].[CATEGORIA](COD_CATEGORIA),
 PRODUTO VARCHAR(20)-- CONSTRAINT UK_PRO_PRO UNIQUE
);

--CRIANDO TABELA ITEM_PRODUTO
CREATE TABLE [TESTE].[DBO].[ITEM_PRODUTO]
( 
 COD_PRODUTO INT,
 COD_MATERIA_PRIMA INT,
 QUANTIDADE INT, --CONSTRAINT NN_ITEPRO_QDE NOT NULL,
 CONSTRAINT PK_ITEPRO_CODPRO_COD_MAT PRIMARY KEY (COD_PRODUTO, COD_MATERIA_PRIMA),
 CONSTRAINT FK_ITEPRO_CODPRO
 FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
 CONSTRAINT FK_ITEPRO_CODMATPRI
 FOREIGN KEY (COD_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA(COD_MATERIA_PRIMA)
);

-- ADICIONANDO CAMPO TIPO_MEDIDA (VARCHAR(30) NA TABELA ITEM_PRODUTO

ALTER TABLE [TESTE].[DBO].[ITEM_PRODUTO]
ADD
TIPO_MEDIDA VARCHAR(30)
;
-- VISUALIZANDO TABELA MODIFICADA
SELECT TOP 1000 [COD_PRODUTO]
      ,[COD_MATERIA_PRIMA]
      ,[QUANTIDADE]
      ,[TIPO_MEDIDA]
  FROM [teste].[dbo].[ITEM_PRODUTO]

--ADICIONANDO CONSTRAINT PARA TIPO_MEDIDA ACEITAR APENAS LITRO,KG,UNIDADE

ALTER TABLE [TESTE].[DBO].[ITEM_PRODUTO]
ADD CONSTRAINT CK_ITEM_PRODUTO_TIPO_MEDIDA CHECK (TIPO_MEDIDA IN ('L','KG','UN'))

ALTER TABLE [TESTE].[DBO].[MATERIA_PRIMA]
ADD CONSTRAINT UN_MATERIA_PRIMA_MATERIA_PRIMAA UNIQUE (MATERIA_PRIMAA)

--VISUALIZAR TODAS AS CONSTRAINTS CRIADAS E ALTERADAS
select * from information_schema.table_constraints;

--EXERCICIO AULA 3 PARTE2 - TRABALHANDO COM SEQUENCE
--CRIAR SEQUENCE
CREATE SEQUENCE SEQ_CATEGORIA_COD_CATEGORIA
AS BIGINT
  START WITH 1
  INCREMENT BY 10
  MINVALUE 1
  MAXVALUE 99999
  NO CYCLE
  CACHE 10;
  --DROP SEQUENCE
  DROP SEQUENCE SEQ_CATEGORIA_COD_CATEGORIA;
  --vERIFICA NOVO VALOR DA SEQUENCIA
SELECT NEXT VALUE FOR SEQ_CATEGORIA_COD_CATEGORIA;

INSERT INTO [TESTE].[DBO].[CATEGORIA]
VALUES (1,'DOCE')

INSERT INTO [TESTE].[DBO].[CATEGORIA] (COD_CATEGORIA, CATEGORIA)
VALUES ( NEXT VALUE FOR SEQ_CATEGORIA_COD_CATEGORIA,'BALAS');--BASICAMENTE A SEQUENCIA ENTRA NO LUGAR DE COD_CATEGORIA
--VERIFICA VALORES INSERIDOS
SELECT TOP 100 [COD_CATEGORIA]
      ,[CATEGORIA]
  FROM [teste].[dbo].[CATEGORIA]
