--AULA 04 EXERCICIO

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';
--CRIANDO TABELA CIENTISTA
CREATE TABLE CIENTISTA 
(

CODIGO NUMBER(4) CONSTRAINT PK_CIENTISTA_CODIGO PRIMARY KEY,
NOME VARCHAR2(50) CONSTRAINT NN_CIENTISTA_NOME NOT NULL,
DT_NASC DATE,
SEXO CHAR(1) CONSTRAINT CK_CIENTISTA_SEXO CHECK (SEXO IN ('M','F'))
)
--INSERINDO VALORES
INSERT INTO CIENTISTA
VALUES (1010, 'STEPHEN HAWKING', '08/01/1942', 'M');

INSERT INTO CIENTISTA
VALUES (1011, 'ALBERT EINSTEIN', '14/03/1879', 'M');

INSERT INTO CIENTISTA
VALUES (1012, 'ISAAC NEWTON', '04/01/1643', 'M');

INSERT INTO CIENTISTA
VALUES (1013, 'GALILEU GALILEI', '15/02/1564', 'M');

INSERT INTO CIENTISTA
VALUES (1014, 'NICOLAU COPERNICO', '19/02/1473', 'M');

--CRIANDO TABELA CLIENTE
CREATE TABLE CLIENTE
(

CODIGO NUMBER(4) CONSTRAINT PK_CLIENTE_CODIGO PRIMARY KEY,
NOME VARCHAR2(50) CONSTRAINT NN_CLIENTE_NOME NOT NULL
)

--INSERINDO CODIGO E NOME DA TABELA CIENTISTA DENTRO DE CLIENTE UTILIZANDO UM COMANDO INSERT
INSERT INTO CLIENTE 
SELECT CODIGO,NOME FROM CIENTISTA

--ALTERANDO A TABELA CIENTISTA INSERINDO A COLUNA DATA DE NASCIMENTO
ALTER TABLE CIENTISTA
ADD DT_OBTIDO DATE	--APOSTILA AULA 03 PAGINA 14
--ALTERANDO O NOME DA COLUNA DE DT_OBTIDO PARA OBITO
ALTER TABLE CIENTISTA
RENAME COLUMN DT_OBTIDO TO DT_OBITO
 --EXIBINDO VALORES DE CIENTISTA
SELECT * FROM CIENTISTA	

--ATUALIZANDO A TABELA CIENTISTA COM AS DATAS DE OBITO
UPDATE CIENTISTA
        SET DT_OBITO = '14/03/2018'
 WHERE CODIGO = 1010;	
UPDATE CIENTISTA
        SET DT_OBITO = '31/03/1727'
 WHERE CODIGO = 1012;
 
  UPDATE CIENTISTA
        SET DT_OBITO = '08/01/1642'
 WHERE CODIGO = 1013;
 
 UPDATE CIENTISTA
        SET DT_OBITO = '21/05/1543'
 WHERE CODIGO = 1014;	
UPDATE CIENTISTA
        SET DT_OBITO = '18/04/1955'
 WHERE CODIGO = 1011;
 
 --EXIBINDO VALORES DE CIENTISTA
SELECT * FROM CIENTISTA	

--INSERINDO DATA DE NASCIMENTO NA TABELA CLIENTE
ALTER TABLE CLIENTE
ADD DT_NASC DATE

 --EXIBINDO VALORES DE cLIENTE
SELECT * FROM CLIENTE

--ATUALIZANDO OS DATAS DE NASCIMENTO DE CLIENTE COM AS DATAS DA TABELA CIENTISTA
UPDATE CLIENTE
   SET DT_NASC = (SELECT DT_NASC FROM CIENTISTA WHERE CLIENTE. DT_NASC = CIENTISTA. DT_NASC);
   
 --EXEMPLOS DE DELETE  
DELETE FROM CIENTISTA
 WHERE TO_CHAR(DT_NASC, 'MONTH') <> 'FEVEREIRO';

DELETE FROM CIENTISTA
WHERE EXTRACT(MONTH FROM DT_NASC) != 2

DELETE FROM CIENTISTA
 WHERE COD NOT IN (1013, 1014);

DELETE FROM CLIENTE
 WHERE CLIENTE.CODIGO NOT IN (SELECT CODIGO FROM CIENTISTA);

--DESAFIO
DELETE FROM CLIENTE
 WHERE CLIENTE.CODIGO NOT IN (SELECT CODIGO FROM CIENTISTA);